In [1]:
import pandas as pd

In [3]:
landslides = pd.read_csv('landslides_lat_long.csv')
landslides.head()

,UNIQUE_ID,Long,Lat,DATE,MOVE_CLASS,Annual_Cos,Repair_Cos
0,LS_0,-120.605220,45.740253,6/20/07,Rockfall,47.680000,1285220.00000
1,LS_1,-120.546074,45.718373,6/20/07,Debris Flow,237.110001,98678.60156
2,LS_2,-120.481975,45.687228,3/29/07,Rockfall,47.680000,13793600.00000
3,LS_3,-120.404544,45.692551,6/20/07,Debris Flow,246.259994,98678.60156
4,LS_4,-120.381816,45.693490,6/21/07,Rockfall,47.680000,2592600.00000

In [4]:
geo_info = pd.read_csv('GeologicDataLandlsides.csv')

In [5]:
landslides_geo = landslides.merge(geo_info,on=u'UNIQUE_ID')

In [6]:
landslides_geo.head()

,UNIQUE_ID,Long,Lat,DATE_x,MOVE_CLASS,Annual_Cos,Repair_Cos,X,Y,REF_ID_COD,...,MAP_UNIT_N,G_MRG_U_L,GEO_GENL_U,AGE_NAME,TERRANE_GR,FORMATION,MEMBER,UNIT,G_ROCK_TYP,nlcd_2006_
0,LS_0,-120.605220,45.740253,6/20/07,Rockfall,47.680000,1285220.00000,1285467.394,1454567.759,ODOT2011,...,Frenchman Springs Member,vol.M.cr.wp.fs.nd.bas,volcanic rocks,Miocene,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,41
1,LS_1,-120.546074,45.718373,6/20/07,Debris Flow,237.110001,98678.60156,1300566.281,1446574.309,ODOT2011,...,Frenchman Springs Member,vol.M.cr.wp.fs.nd.bas,volcanic rocks,Miocene,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,81
2,LS_2,-120.481975,45.687228,3/29/07,Rockfall,47.680000,13793600.00000,1316943.110,1435213.605,ODOT2011,...,Frenchman Springs Member,vol.M.cr.wp.fs.nd.bas,volcanic rocks,Miocene,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,41
3,LS_3,-120.404544,45.692551,6/20/07,Debris Flow,246.259994,98678.60156,1336731.661,1437168.634,ODOT2011,...,Frenchman Springs Member,vol.M.cr.wp.fs.nd.bas,volcanic rocks,Miocene,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,41
4,LS_4,-120.381816,45.693490,6/21/07,Rockfall,47.680000,2592600.00000,1342539.547,1437518.348,ODOT2011,...,Frenchman Springs Member,vol.M.cr.wp.fs.nd.bas,volcanic rocks,Miocene,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,42

In [10]:
slope = pd.read_csv('SlopeData.csv')
slope.head()

   Unnamed: 0            X            Y UNIQUE_ID     Slope
0           0  1285467.394  1454567.759      LS_0   2.61776
1           1  1300566.281  1446574.309      LS_1   2.77631
2           2  1316943.110  1435213.605      LS_2  14.03704
3           3  1336731.661  1437168.634      LS_3   2.61776
4           4  1342539.547  1437518.348      LS_4  29.72073

In [11]:
landslides_sl = landslides_geo.merge(slope,on=u'UNIQUE_ID')

In [12]:
landslides_sl.head()

,UNIQUE_ID,Long,Lat,DATE_x,MOVE_CLASS,Annual_Cos,Repair_Cos,X_x,Y_x,REF_ID_COD,...,TERRANE_GR,FORMATION,MEMBER,UNIT,G_ROCK_TYP,nlcd_2006_,Unnamed: 0,X_y,Y_y,Slope
0,LS_0,-120.605220,45.740253,6/20/07,Rockfall,47.680000,1285220.00000,1285467.394,1454567.759,ODOT2011,...,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,41,0,1285467.394,1454567.759,2.61776
1,LS_1,-120.546074,45.718373,6/20/07,Debris Flow,237.110001,98678.60156,1300566.281,1446574.309,ODOT2011,...,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,81,1,1300566.281,1446574.309,2.77631
2,LS_2,-120.481975,45.687228,3/29/07,Rockfall,47.680000,13793600.00000,1316943.110,1435213.605,ODOT2011,...,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,41,2,1316943.110,1435213.605,14.03704
3,LS_3,-120.404544,45.692551,6/20/07,Debris Flow,246.259994,98678.60156,1336731.661,1437168.634,ODOT2011,...,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,41,3,1336731.661,1437168.634,2.61776
4,LS_4,-120.381816,45.693490,6/21/07,Rockfall,47.680000,2592600.00000,1342539.547,1437518.348,ODOT2011,...,Columbia River Basalt Group,Wanapum Basalt,Frenchman Springs Member,no data,basalt,42,4,1342539.547,1437518.348,29.72073

In [13]:
landslides_sl.to_csv('landslides_noweather.csv')